### ISSUE TITLE
Are these these patterns mostly for library use  

### ISSUE THREAD

**Issue by Gregjarvez** [kentcdodds/advanced-react-patterns-v2#1]
Hello Kent. I have studied and love these react patterns however I barely find a use case for most of them them in my daily work with react but recognise them used all over the place in react libraries.
Is there something i need to know to use these more.

Thanks :)

**Comment by kentcdodds** [comment]
I definitely use these patterns in my non-library code all the time. If it's useful for a library component then it's probably useful in a regular application component as well. Code reuse is only one reason to use some of these patterns (though it's probably the biggest). I like to use these patterns to help separate concerns of my components.

Good luck!
