### ISSUE TITLE
"npm i" shows 40 vulnerabilities

### ISSUE THREAD

**Issue by plug-n-play** [kentcdodds/advanced-react-patterns-v2#27]
Thanks Kent & other contributors for all your efforts. Just wanted to point out security vulnerabilities npm reports as it completes (please note there isn't any issue with the installation):

![image](https://user-images.githubusercontent.com/6245927/40022409-8c834038-57e5-11e8-8b5d-25056b82e481.png)

Here is the summary of npm audit - https://file-eqqipuzafp.now.sh/

Environment Details:
OS: macOS Sierra - 10.12.6
Node: v8.9.1
NPM: v6.0.1

**Comment by kentcdodds** [comment]
Thanks for the issue. All of the vulnerabilities are dependencies of `react-scripts` so we can't do anything about that directly. Please file this issue on create-react-app. Thanks!

Make sure to note [our version in this project is `2.0.0-next.b2fd8db8`](https://github.com/kentcdodds/advanced-react-patterns-v2/blob/d243c76dd2863f781737035e7496817fc0d2a515/package.json#L27). Thanks again!
