### ISSUE TITLE
First exercise - 01: Switch button never change its state!

### ISSUE THREAD

**Issue by hawaijar** [kentcdodds/advanced-react-patterns-v2#28]
Hello,

I was going through the codesandbox link - https://codesandbox.io/s/github/kentcdodds/advanced-react-patterns-v2 to quickly go through the exercises. I'm in the first exercise and for some reason, the toggle button didn't change its state though I applied the setState appropriately. BTW, the final exercise also exhibited the same behavior. Am I missing anything?

Oh, yes the toggle() looks same as it's there in the final exercise of 01.

Thanks,
KSM

**Comment by hawaijar** [comment]
Yup, that works! 😊

**Comment by ofhouse** [comment]
Nice 😊
Looked a bit more into it and it seems like there was a regression in this pull request #26 , where the `e.preventDefault()` call was [unintentionally removed](https://github.com/kentcdodds/advanced-react-patterns-v2/pull/26/files#diff-aa14da87bc15f427f7c4e3326f1bbda8L11).

I made a pull-request #29 which should fix the problem in the future.

**Comment by kentcdodds** [comment]
Sorry about that! Thanks for the help!
