### ISSUE TITLE
Toggle button's behavior - discrepancy between codesandbox and local

### ISSUE THREAD

**Issue by hawaijar** [kentcdodds/advanced-react-patterns-v2#30]
Hello Team,

In codesandbox, the toggle button 'onClick' is expectedly fired on single click where as in my local m/c - which I clone from  https://github.com/kentcdodds/advanced-react-patterns-v2.git (tested up to 03.js), it's triggered only on 'double click'. I wonder, what on earth is going on? 😕

Note: I'm using Mac Air (and testing on Chrome) and I don't think it's because of the system otherwise I would expect consistent behavior in codesandbox too.

Thanks,
KSM

**Comment by kentcdodds** [comment]
Rats. I'll look into it. If you're following along with Frontend Masters make sure to follow the instructions in the README for that.
