### ISSUE TITLE
Running app locally breaks after page refresh

### ISSUE THREAD

**Issue by sethbergman** [kentcdodds/advanced-react-patterns-v2#36]
I've cloned the code sandbox as well as this repository to confirm this behavior. After completing the setup and starting the app locally, the pages do not display after hitting refresh in the browser.

_node  v10.4.0_
_npm v6.1.0_
_Linux 4.13.0-45-generic #50~16.04.1-Ubuntu x86_64 GNU/Linux_

**Comment by kentcdodds** [comment]
Hmmm... It seems to work fine for me. Could you do a little more digging? Perhaps this is a bug in create-react-app?

**Comment by sethbergman** [comment]
I've made a short video:
[Refresh breaks page reloads - CodeSandbox](https://youtu.be/UsYN7zZLBz0)

**Comment by sethbergman** [comment]
I've confirmed that it's only an issue with CodeSandbox, not your repository. Sorry for the confusion.

**Comment by kentcdodds** [comment]
Ah, yeah, that's probably an issue with codesandbox-client. You could [file an issue there](https://github.com/CompuIves/codesandbox-client/issues/new).

Thanks for your patience and digging!
