### ISSUE TITLE
Component with React.createContext() used in older version of react

### ISSUE THREAD

**Issue by adyz** [kentcdodds/advanced-react-patterns-v2#41]
Hey Kent, 

Awesome workshop!

I am building a similar component using `React.createContext()`, but I want use the component in an older project that uses react 16.0.0 and errors on `createContext` because this was introduced later.

Is there any recommended way to polyfill this?

Thank you!

**Comment by kentcdodds** [comment]
I recommend https://npmjs.com/package/create-react-context :+1:

I'm glad you like the workshop!
