### ISSUE TITLE
Add extra credit for exercise 02

### ISSUE THREAD

**Issue by 01abhishekjain** [kentcdodds/advanced-react-patterns-v2#43]
Just a reminder for you to add the extra credit for the scenario in which the consumer of the compound component is required to be able to add their own HTML tags as children.

i.e. being able to do this in the usage section:

```
  <Toggle onToggle={onToggle}>
      <Toggle.On>The button is on</Toggle.On>
      <Toggle.Off>The button is off</Toggle.Off>
      <Toggle.Button />
      <span>Something</span>
    </Toggle>
```

😃

**Comment by kentcdodds** [comment]
Thanks @01abhishekjain! I've added a note for the extra credit :)
