### ISSUE TITLE
HOC Exercise fails even though my code matches the video

### ISSUE THREAD

**Issue by EddyVinck** [kentcdodds/advanced-react-patterns-v2#50]
I stumbled upon something. My code for the HOC matches the code in the video, but the tests still fail. The code in /exercises-final is different and passes the tests. Why? Did the hoistNonReactStatics API change?

My code:
```jsx
function withToggle(Component) {
  const Wrapper = React.forwardRef((props, ref) => {
    return (
      <Toggle.Consumer>
        {(toggleUtils) => (
          <Component {...props} toggle={toggleUtils} ref={ref} />
        )}
      </Toggle.Consumer>
    );
  });
  Wrapper.displayName = `withToggle(${Component.displayName ||
    Component.name})`;
  hoistNonReactStatics(Wrapper, Component);

  return Wrapper;
}
```
The code above is the exact same code as in the course (FEM) but the tests are still failing. What's going on?

The code in /exercises-final
```jsx
function withToggle(Component) {
  function Wrapper(props, ref) {
    return (
      <Toggle.Consumer>
        {(toggleContext) => (
          <Component {...props} toggle={toggleContext} ref={ref} />
        )}
      </Toggle.Consumer>
    );
  }
  Wrapper.displayName = `withToggle(${Component.displayName ||
    Component.name})`;
  return hoistNonReactStatics(React.forwardRef(Wrapper), Component);
}
```

This is what the tests are saying:

![image](https://user-images.githubusercontent.com/23434753/47602159-c66e1080-d9da-11e8-9d48-8c04801ac704.png)

**Comment by gpetrioli** [comment]
It is not the **exact** same code.  

In the working code the `displayName` is applied to the `Wrapper` element before being passed to `React.forwardRef` while in your code you apply the `displayName` to the returned object so it is not associated with the actual component that gets rendered. You could log the `Wrapper` variable in both cases and you will see the difference.

**Comment by EddyVinck** [comment]
Thank you for looking into this. I will post an update when I work on this course again, which is probably this weekend or earlier.

**Comment by kentcdodds** [comment]
Thanks @gpetrioli!
